### ISSUE TITLE
[4.x] Plugin not working for Craft 4.12

### ISSUE THREAD

**Issue by anita-chouhan** [marionnewlevant/craft-twig_perversion#31]
We upgraded the Craft CMS version from 4.11.5 to 4.12.0 and found the plugin no longer works. A similar [issue](https://github.com/marionnewlevant/craft-twig_perversion/issues/26) was fixed for the Craft 5 version. Kindly let us know if there are any updates planned for version 4.12 and above as well.

**Plugin Version**
3.0.0

**Comment by itsmattsoria** [comment]
@marionnewlevant it looks like those fixes that were addressed for v5 have indeed been merged into the v2 branch, but just haven't been added to a release? https://github.com/marionnewlevant/craft-twig_perversion/compare/v3.0.0...v2 

I'm not sure if that's exactly accurate, but it seems like it may just require being added as a release in order to be updated with those fixes for Craft 4 sites?

**Comment by moldedjelly** [comment]
I'm seeing this issue too - using Craft 4.14.2

I tried to update my composer to reference the branch "v2.x-dev" but the twig ended up outputting stuff like this:

"[RETURN_MARKER:2078273842]" where I was expecting some simple string being returned from a macro

Is there anyway to resolve this issue without bumping Craft version back?

**Comment by anita-chouhan** [comment]
As of now, we can use the `v2` branch, which works for Craft 4 as [suggested](https://github.com/marionnewlevant/craft-twig_perversion/issues/26#issuecomment-2573771994) by @brandonkelly.

**Comment by moldedjelly** [comment]
thanks @anita-chouhan I just followed Brandon's specific instructions on updating composer and still getting that strange "[RETURN_MARKER:2078273842]" coming back from macros that are using {% return %}

**Comment by moldedjelly** [comment]
so to be more specific again with my code, below is my twig test...

`{% macro getYear() %}
	{% return now|date("Y") %}
{% endmacro %}
{{ _self.getYear() }}`

and it renders:
[RETURN_MARKER:444504989]

when I'm expecting it to render:
2025

**Comment by brandonkelly** [comment]
Twig 3.15 (used by Craft 4.14 and 5.6) [refactored how macros are compiled](https://github.com/twigphp/Twig/pull/4402), which broke my previous changes.

Here’s updated PRs that works on both Twig 3.14 and 3.15: 

- Craft 4: https://github.com/marionnewlevant/craft-twig_perversion/pull/34
- Craft 5: https://github.com/marionnewlevant/craft-twig_perversion/pull/35

Until they’re merged, you can switch to my fork by adding the following to your `repositories` array in `composer.json`:

```json
{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/brandonkelly/craft-twig_perversion"
        }
    ]
}
```

Then change your `marionnewlevant/twig-perversion` requirement to:

- Craft 4: `"marionnewlevant/twig-perversion": "v2.x-dev",`
- Craft 5: `"marionnewlevant/twig-perversion": "v5.x-dev",`

Then run `composer update`.

You’ll also need to clear your compiled Twig templates from the Caches utility in the control panel, or by running the following command:

```sh
php craft clear-caches/compiled-templates
```

**Comment by moldedjelly** [comment]
thanks @brandonkelly I tried your steps that @anita-chouhan pointed me to before, so I've now tried your steps above - updating composer to point to the repo and the branch. I hadn't been clearing compiled templates before, so I ran that command also and got the output "Clearing cache: Compiled templates".

Then I ran the following twig code in "templates/test-twig.twig"
`{% macro getYear() %}
	{% return now|date("Y") %}
{% endmacro %}
{{ _self.getYear() }}`

and hitting the url "/test-twig" the render output is still:
[RETURN_MARKER:533134766]

**Comment by brandonkelly** [comment]
@moldedjelly Search for `"name": "marionnewlevant/twig-perversion"` in your `composer.lock` file. What is the `source` object that follows it?

If you’re using my fork, it should be:

```json
"source": {
    "type": "git",
    "url": "https://github.com/brandonkelly/craft-twig_perversion",
    "reference": "37e22d8eda2088b01ffaf9bc89cc059317d48a54"
},
```

**Comment by moldedjelly** [comment]
I'm running Craft 4.14.2
my lock file is showing this:

...
            "name": "marionnewlevant/twig-perversion",
            "version": "v2.x-dev",
            "source": {
                "type": "git",
                "url": "https://github.com/marionnewlevant/craft-twig_perversion.git",
                "reference": "f3ef32731d65a7c47b0925814fa6207674cbf3a1"
            },
...

which seems to line up with the latest commit on v2?

after clearing composer cache, clearing vendor/* then composer install, tried running /test-twig again and still same problem output

**Comment by moldedjelly** [comment]
ok I found my mistake
@brandonkelly I wasn't referencing your repo https://github.com/brandonkelly/craft-twig_perversion
updated that and it's working now yay!

**Comment by brandonkelly** [comment]
Glad to hear it’s working now!

I’m not sure how much longer those changes will keep working, so you’re still probably best off moving away from this plugin. See https://nystudio107.com/blog/making-twig-macros-work-like-functions and https://github.com/marionnewlevant/craft-twig_perversion/pull/27#issuecomment-2494040375 for alternative approaches.

In your example (assuming there’s not more to it than you posted), you could simplify it to:

```twig
{% macro getYear() %}
  {{- now|date("Y") -}}
{% endmacro %}
```

**Comment by moldedjelly** [comment]
Thanks @brandonkelly, I've now converted everything over either to the json_encode method from nystudio107 or your method [suggesting](https://github.com/marionnewlevant/craft-twig_perversion/pull/27#issuecomment-2494040375) using the _globals collection - which is very handy for passing objects around
